apiVersion: v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 3
  template:
    metadata:
      name: pod-test
    spec:
      containers:
      - name: ctn-test
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  type: LoadBalancer
  ports:
  - port: 80            # LB 의 포트가 됨!!! = Cluster-IP 포트가 됨
    targetPort: 80

